-- SQLite
SELECT CARS.NAME, CARS.YEAR, CARS.KM, CARS.COLOR, CARS.STATUS, CAR_MODELS.MODEL_NAME AS 'MODELO', CAR_BRANDS.BRAND_NAME as 'MARCA'
FROM CARS
INNER JOIN CAR_MODELS on(CARS.MODEL_ID = CAR_MODELS.ID)
INNER JOIN CAR_BRANDS on(CARS.BRAND_ID = CAR_BRANDS.ID);