-- SQLite
SELECT L.START_DATE AS 'INICIO', L.END_DATE AS 'TÉRMINO', L.TOTAL, C.NAME AS 'CLIENTE', CR.NAME AS 'CARRO', E.NAME AS 'FUNCIONÁRIO' 
FROM LOCATIONS AS L
INNER JOIN CUSTOMERS AS C ON (L.CAR_ID = C.ID)
INNER JOIN CARS AS CR ON (L.CAR_ID = CR.ID)
INNER JOIN EMPLOYEES AS E ON (L.EMPLOYEE_ID = E.ID);